const START_REQUEST = 'app/START_REQUEST';
const START_REQUEST_SUCCESS = 'app/START_REQUEST_SUCCESS';
const START_REQUEST_FAILURE = 'app/START_REQUEST_FAILURE';

export {START_REQUEST, START_REQUEST_SUCCESS, START_REQUEST_FAILURE};
