export const columns = [
  {
    key: "name",
    label: "NAME",
  },
  {
    key: "role",
    label: "ROLE",
  },
  {
    key: "status",
    label: "STATUS",
  },
  {
    key: "action",
    label: "ACTIONS",
  },
];

export const transactionColumns = [
  {
    key: "name",
    label: "NAME",
  },
  {
    key: "amount",
    label: "AMOUNT",
  },
  {
    key: "status",
    label: "STATUS",
  },
  {
    key: "transactionType",
    label: "TRANACTION TYPE",
  },
  {
    key: "action",
    label: "ACTIONS",
  },
];

export const testUsers = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
];

export const testTransactions = [
  {
    key: "1",
    name: "Tony Reichert",
    email: "test@gmail.com",
    role: "CEO",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "2",
    name: "Zoey Lang",
    role: "Technical Lead",
    status: "Paused",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "3",
    name: "Jane Fisher",
    role: "Senior Developer",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "4",
    name: "William Howard",
    role: "Community Manager",
    status: "Vacation",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "5",
    name: "Emily Collins",
    role: "Marketing Manager",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "6",
    name: "Brian Kim",
    role: "Product Manager",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "7",
    name: "Laura Thompson",
    role: "UX Designer",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "8",
    name: "Michael Stevens",
    role: "Data Analyst",
    status: "Paused",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "9",
    name: "Sophia Nguyen",
    role: "Quality Assurance",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "10",
    name: "James Wilson",
    role: "Front-end Developer",
    status: "Vacation",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "11",
    name: "Ava Johnson",
    role: "Back-end Developer",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "12",
    name: "Isabella Smith",
    role: "Graphic Designer",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "13",
    name: "Oliver Brown",
    role: "Content Writer",
    status: "Paused",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "14",
    name: "Lucas Jones",
    role: "Project Manager",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "15",
    name: "Grace Davis",
    role: "HR Manager",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "16",
    name: "Elijah Garcia",
    role: "Network Administrator",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "17",
    name: "Emma Martinez",
    role: "Accountant",
    status: "Vacation",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "18",
    name: "Benjamin Lee",
    role: "Operations Manager",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "19",
    name: "Mia Hernandez",
    role: "Sales Manager",
    status: "Paused",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "20",
    name: "Daniel Lewis",
    role: "DevOps Engineer",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "21",
    name: "Amelia Clark",
    role: "Social Media Specialist",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "22",
    name: "Jackson Walker",
    role: "Customer Support",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "23",
    name: "Henry Hall",
    role: "Security Analyst",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "24",
    name: "Charlotte Young",
    role: "PR Specialist",
    status: "Paused",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
  {
    key: "25",
    name: "Liam King",
    role: "Mobile App Developer",
    status: "Active",
    amount: 100,
    points: 100,
    transactionType: "Bill",
    transactionRef: Math.random(5),
    receipientName: "Admin",
    cashbackAmount: 10,
    fee: 0,
    date: new Date(),
    email: "test@gmail.com",
  },
];
