const LOGIN_REQUEST = 'app/LOGIN_REQUEST';
const LOGIN_REQUEST_SUCCESS = 'app/LOGIN_REQUEST_SUCCESS';
const LOGIN_REQUEST_FAILURE = 'app/LOGIN_REQUEST_FAILURE';

export {LOGIN_REQUEST, LOGIN_REQUEST_SUCCESS, LOGIN_REQUEST_FAILURE};
