const JEJE_REQUEST = 'app/JEJE_REQUEST';
const JEJE_REQUEST_SUCCESS = 'app/JEJE_REQUEST_SUCCESS';
const JEJE_REQUEST_FAILURE = 'app/JEJE_REQUEST_FAILURE';

export {JEJE_REQUEST, JEJE_REQUEST_SUCCESS, JEJE_REQUEST_FAILURE};
